my-server:
  domain: 123

server:
  port: 9090

spring:
  application:
    name: steam-cert

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/usermanager
    username: postgres
    password: postgres

  redis:
    # Redis 数据库索引（默认为 0）
    database: 0
    host: localhost
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password:
    # springboot 2.0 redis默认客户端已换成lettuce
    timeout: 5000

  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 47.94.163.139
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://www.xuyachang.xyz:7001/eureka/

mybatis:
  mapperLocations: classpath:com.xu.mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

logging:
  file.name: weSteam.log
  level:
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    com.xu: DEBUG

#dubbo:
#  application:
#    name: we-steam-certificate
#  registry:
#    address: 47.94.163.139:2181
#    protocol: zookeeper
#  protocol:
#    name: dubbo
#    port: 20882
#  monitor:
#    protocol: registry